### ISSUE TITLE
Help with setting up a trait like system

### ISSUE THREAD

**Issue by 5Mixer** [haxetink/tink_lang#11] opened 2015-06-21 08:04 UTC
Hey there, uhh, this isn't really an issue, I just don't know how to get it to work.

I was hoping to use tink to allow me to have certain traits. This is best explained by saying that I need to have interfaces that are automaticly implemented if they are not filled in by the implementer. So I can have an interface, that has methods with contents. Classes that use this interface should be able to override default behaviour, but if they don't, it should use the method described in the interface.

I was told to ask here, so, yeah. I don't know if tink is suitable.
Cheers!

**Comment by back2dos** [comment] 2015-06-21 11:09
Tink's [partial implementations](https://github.com/haxetink/tink_lang#partial-implementation) do just that ;)

**Comment by 5Mixer** [comment] 2015-06-22 06:29
Thanks. This will be a major part of my codes architecture, so I was wondering what the caveats of it actually are. I am still fairly new to haxe and I can't really see what the problem with them is. I also looked at syntactic delegation, which looks like it does a similar thing, although doesn't really fit perfectly into my code. For instance, would you be able to do Std.is on the object to see what it implements? And it would be nice to just say that it implements fooBehaviour, instead of @fwd. so really, what are the caveats of the other system? Thanks, you have been very helpful :+1:

**Comment by 5Mixer** [comment] 2015-06-22 08:30
Oops

**Comment by back2dos** [comment] 2015-06-23 08:01
There are a few issues with partial implementations that are really hard to overcome, most importantly having `using` an `import` declared for the trait work in the "traitee" correctly.

Another issue is that traits are a form of inheritance and composition is preferable.

Take this for example:

```
interface Inner {}

@:tink class Outer implements Inner {
  @:forward var inner:Inner = _;
}
```

The thing stored in `inner` is an actual object. You can inject any behavior from outside, and the outer class just forwards to it. There is a clear separation between the two objects. The inner one knows nothing about the outer one (unless you make it know about it explicitly) while the outer one knows only what is defined by the interface. It avoids the [fragile base class problem](https://en.wikipedia.org/wiki/Fragile_base_class) that traits can cause, by having clear composition of two individually encapsulated objects, rather than mushing together two parts none of which can exist on its own.

I personally believe that syntactic delegation is almost always favorable, but I realize I am being rather opinionated on that one, which is why I added support for partial implementations also - [after being quite pigheaded for a while](https://github.com/back2dos/tinkerbell/issues/32#issuecomment-8255128).

It's for you to tell what works best for you, but I suggest you give syntactic delegation a try ;)

**Comment by 5Mixer** [comment] 2015-06-23 08:06
Thanks again, very much. Do you know if Std.is works with syntactic delegation?

**Comment by back2dos** [comment] 2015-06-23 09:29
In the example I gave, it will work, because `Outer` implements `Inner`. By default, it won't. Say you have this:

```
interface Sword {
  function attack(target:Character):Void;
}

class Character {
  @:forward var sword:Sword;
}
```

In that case it makes sense for `Std.is(someCharacter, Sword)` to return `false`. It is quite powerful to be able to just use some other type's behavior without becoming that type. After all, you wouldn't want one character equipping another as a sword :D

**Comment by 5Mixer** [comment] 2015-06-23 09:36
Yes, hmm, I can see how this might work :) Thanks, that last comment really helped. I just don't like the idea of actually creating a copy of every trait, as a variable (OCD heh) but I think this will be the best way I can really do it with tink. Thanks for your help :) I will come back here if I have trouble with implementation

**Comment by 5Mixer** [comment] 2015-06-23 09:37
"After all, you wouldn't want one character equipping another as a sword :D" I just imagined some chain of characters using each other as weapons in multiplayer, haha!!

**Comment by back2dos** [comment] 2015-06-23 09:50
The thing is, **it's not a trait** anymore with delegation. It is a self-contained object. For the bit of extra noise, you get clearer decomposition of concerns. 

If you are sure that the class you are build *_is a_ specific type and should have the behavior baked into it, instead of composed by injectable objects, then a trait is a better choice and I encourage you to use it. From my experience, if you follow [SOLID](https://en.wikipedia.org/wiki/SOLID_%28object-oriented_design%29), the use case rarely occurs. But as always, it depends, and it's not like you can't use both features. In fact, partial implementations can even use syntactic delegation themselves - within some weird constraints dictated by the compiler non-deterministic typing order though.

**Comment by 5Mixer** [comment] 2015-06-23 21:04
Hmm, well I wasn't really using it for traits, more as an extention of functionality. For instance, I would have had the interface RocketEngine, and then I would have implemented things like onTakeoff, onTravel, onFuelOut, etc, in different engines. But I didn't want to bloat my item classes if I just wanted default behaviour of an engine, which is why I wanted interfaces that allowed implementation. In that way, a cleanRocketEngine actually /is/ a rocket engine. I could do this with normal inheritence chain, but then what if I want a playerWeapon to also be a rocketEngine? I needed something like composition. I think this will actually work really well... Even though I am extending a whole item, not just a single behaviour.

Do you see syntactic delegation as good for this? I think it might work, but not sure. I typed this on my iPad so sorry if the grammar is crap heh.

**Comment by 5Mixer** [comment] 2015-06-23 21:26
Oh, and also, (sorry about the long thread) how am I suppose to have a group of these objects? I mean if they all implement something, I can have a list of that, as the compiler knows that it is a specific type, or has that types attributes? Continuing my last example, how can a racingEngine be in the same list as a cleanEngine? I mean, casting can get messy.

**Comment by back2dos** [comment] 2015-06-24 10:09
I'm sorry, I'm having some trouble to follow you. Could you post some (pseudo)code that illustrates the setup you are trying to achieve?

**Comment by 5Mixer** [comment] 2015-06-24 10:18
Well, it's hard to show a full system, but...
(Sorry I am a little noobish lol)

interface enginePart () {
      onTakeOff () { trace("Taking off!"};};
}
class specialEngine implements enginePart () {
     onTakeOff () { trace("This will be a great take off!"); };
}
class oldlEngine implements enginePart () {
     onTakeOff () { trace("What a slow take off"); };
}
class standardEngine implements enginePart () {
    //This has default onTakeOff functionality.
}
var groupOfEngines:Group;
groupOfEngines -> add(var specialEngine)
groupOfEngines -> add(var oldEngine)
groupOfEngines -> add(var standardEngine)

for (allEngines in groupOfEngines) {
    allEngines.takeOff();
}
//That printed
///This will be a great take off
//What a slow take off
///Taking off!

**Comment by back2dos** [comment] 2015-06-24 10:54
The take off code:

```
var hornyEngine = new EngineWithHorn();//ooooh

var groupOfEngines:Array<EnginePart> = [
   new SpecialEngine(),
   new OldEngine(),
   new StandardEngine(),
   hornyEngine,
];

for (e in groupOfEngines)
   e.takeOff();

hornyEngine.honk();
```

With partial implementation:

```
@:tink interface EnginePart {
   function onTakeOff():Void trace("taking off");
}

class SpecialEngine implements EnginePart {
   public function onTakeOff() trace("taking off");
   public function new() {}
}

class OldEngine implements EnginePart {
   public function onTakeOff() trace("taking off");
   public function new() {}
}

class StandardEngine implements EnginePart {
   public function new() {}
}

class EngineWithHorn implements EnginePart {
   public function new() {}
   public function honk() trace("meeeeeeeeeep");
}
```

With delegation:

```
interface EnginePart {
   function onTakeOff():Void;
}

class SpecialEngine implements EnginePart {
   public function onTakeOff() trace("taking off");
   public function new() {}
}

class OldEngine implements EnginePart {
   public function onTakeOff() trace("taking off");
   public function new() {}
}

class StandardEngine implements EnginePart {
   public function onTakeOff() trace("taking off");
   public function new() {}
}

class Horn {
   public function new() {}
   public function honk() trace("meeeeeeeeeep");
}

@:tink class EngineWithHorn implements EnginePart {
   @:forward var engine = new StandardEngine();
   @:forward var horn = (new Horn());//this becomes an optional constructor argument
   public function new() {}
}
```

In the later case, you can now do `new EngineWithHorn(new BigHorn())` with something like:

```
class BigHorn extends Horn {
   override function honk() trace("MEEEEEEEEEEEP");
}
```

While in both cases you get exactly the same interfaces, in the latter it's easier to inject implementations, which usually proves rather powerful down the road.

Does that clarify things?

**Comment by 5Mixer** [comment] 2015-06-24 20:55
Yes, your an absolute legend! Thank you so much for help with this. When I get home from school I will try the second method. Thank you!

**Comment by 5Mixer** [comment] 2015-06-24 21:13
Hmm, also, do I have to make a new interface for everything I forward if I wish to iterate through it in a group? Can I not just loop through everything that forwards a specific class?
I hope I can, because there will be many many types of items in my project. :)

**Comment by 5Mixer** [comment] 2015-06-26 10:58
I tried getting this working, but am just getting an ugly error. Here is my code: http://hastebin.com/cahekequza.hx
and the error in console says:
lime test neko
/usr/lib/haxe/lib/tink_syntaxhub/0,3,0/src/tink/syntaxhub/FrontendContext.hx:14: characters 1-23 : Class not found : ImportExpr
/usr/lib/haxe/lib/tink_lang/0,3,0/src/tink/lang/Sugar.hx:18: lines 18-291 : Defined in this class
/usr/lib/haxe/lib/tink_syntaxhub/0,3,0/src/tink/SyntaxHub.hx:28: characters 25-49 : Class<tink.syntaxhub.FrontendContext> has no field findType
/usr/lib/haxe/lib/tink_syntaxhub/0,3,0/src/tink/SyntaxHub.hx:29: characters 2-28 : Class<haxe.macro.Compiler> has no field addGlobalMetadata
/usr/lib/haxe/lib/tink_syntaxhub/0,3,0/src/tink/SyntaxHub.hx:61: characters 10-33 : Class<tink.syntaxhub.FrontendContext> has no field plugins
export/mac64/neko/haxe/ApplicationMain.hx:205: characters 2-7 : Build failure

Building with haxeflixel lib by the way, hope you can help :)

**Comment by back2dos** [comment] 2015-06-26 11:00
For starters, can you please `haxelib update tink_syntaxhub`?

**Comment by 5Mixer** [comment] 2015-06-26 11:02
Yep just did that, no difference. I am meant to import tink_lang right?

PS. Holy moly, do I have to pay for support or something because that reply was /fast/

**Comment by back2dos** [comment] 2015-06-26 11:05
You should not be importing anything. You have to compile with `-lib
tink_lang`.

The errors are probably caused by imports in fact. Somehow, something from
the macro context is imported where it shouldn't.

**Comment by back2dos** [comment] 2015-06-26 11:06
Oh, and you can buy me a beer at the next WWX, if you wish ;)

**Comment by 5Mixer** [comment] 2015-06-26 11:08
With haxeflixel when I add other libraries I put < haxelib name="flixel"/ > in this XML file. I tried with the command line lib, and it runs as if tink just wasn't there, saying that there isn't a take off method.

**Comment by 5Mixer** [comment] 2015-06-26 11:09
I'm not doing any import tink_langs or anything, just that one thing in the XML.
Also, it seems even removing all the macro stuff throws the error... maybe I should try without haxeflixel?

**Comment by back2dos** [comment] 2015-06-26 11:16
Ok, two issues:
1. It should be `@:fwd` not `@fwd` (noticee the colon)
2. I see now that in the doc I said the `@:fwd` shortcut should work, but actually forgot to implement it. Can you please try `@:forward` for the time being?

This code compiles for me (try with `haxe -lib tink_lang -main Main --interp`):

```
//Main.hx
package ;
@:tink class RocketEngine {
  public function new() {}
  public function takeOff () { trace("The default is taking off. Vroom vroom.");};
}

@:tink class EcoEngine {
  @:forward var engine = new RocketEngine();
  public function new() {}
}

class Main {
  static function main() {
    var ecoEngine:EcoEngine = new EcoEngine();
    ecoEngine.takeOff();        
  }
}
```

**Comment by 5Mixer** [comment] 2015-06-26 11:20
Gee, really stumped at whats going on. Tried your code, new file with that script, in different directory, and get...
haxe -lib tink_lang -main Main --interp
/usr/lib/haxe/lib/tink_syntaxhub/0,3,3/src/tink/syntaxhub/FrontendContext.hx:14: characters 1-23 : Class not found : ImportExpr
/usr/lib/haxe/lib/tink_lang/0,3,0/src/tink/lang/Sugar.hx:18: lines 18-291 : Defined in this class
/usr/lib/haxe/lib/tink_syntaxhub/0,3,3/src/tink/SyntaxHub.hx:28: characters 25-49 : Class<tink.syntaxhub.FrontendContext> has no field findType
/usr/lib/haxe/lib/tink_syntaxhub/0,3,3/src/tink/SyntaxHub.hx:29: characters 2-28 : Class<haxe.macro.Compiler> has no field addGlobalMetadata
/usr/lib/haxe/lib/tink_syntaxhub/0,3,3/src/tink/SyntaxHub.hx:61: characters 10-33 : Class<tink.syntaxhub.FrontendContext> has no field plugins
Main.hx:16: characters 4-21 : EcoEngine has no field takeOff
:/

**Comment by back2dos** [comment] 2015-06-26 11:21
Uhm ok. Different question: what's your Haxe version? :D

**Comment by 5Mixer** [comment] 2015-06-26 11:23
Haxe Compiler 3.1.3 - (C)2005-2014 Haxe Foundation

**Comment by 5Mixer** [comment] 2015-06-26 11:23
ooohhh....

**Comment by back2dos** [comment] 2015-06-26 11:25
Yeah, thought as much. I'm sorry, but tink requires Haxe 3.2.0 to work ;)

**Comment by 5Mixer** [comment] 2015-06-26 11:30
You have no idea how long I have spent on figuring out issues that have just been about wrongs versions. Not just in haxe but in all programming. _Sigh_ :P

"Main.hx:5: The default is taking off. Vroom vroom." Woo!! Your support has been really, really great! Thanks so much :D Your awesome at this! Cheers.

**Comment by back2dos** [comment] 2015-06-26 11:31
No problem. Now go forth, and have fun! ;)

**Comment by 5Mixer** [comment] 2015-06-26 11:32
Wait wait! heh! Noo.

**Comment by 5Mixer** [comment] 2015-06-26 11:32
Hmm, also, do I have to make a new interface for everything I forward if I wish to iterate through it in a group? Can I not just loop through everything that forwards a specific class?
I hope I can, because there will be many many types of items in my project. :)

**Comment by back2dos** [comment] 2015-06-26 11:34
Oh, right. You asked that already. I remember not understanding it the first time :D

How about some more pseudo-code to show what you'd like to work?

**Comment by 5Mixer** [comment] 2015-06-26 11:39
Yeah so you posted this iterative code, which is able to iterate because the interface tells the compiler which methods it has. Am I able to let the compiler loop through objects that aren't actually marked as using an interfacing but rather @:forwarding an object? Because of course in both cases the computer should be able to tell what methods it has. I mean, I can always make lots of interfaces (and I will if there is no alternative) but if there is so cast thing, that would be nice to know about.

Eg:

var groupOfEngines:Array<EnginePart> = [
   new SpecialEngine(),
   new OldEngine(),
];

for (e in groupOfEngines) //Somehow let it know that it forwards x with y members (takeOff)
   e.takeOff();

/\* Doesn't need below to work
@:tink interface EnginePart {
   function onTakeOff():Void trace("taking off");
}
*/
Hope you understand :)

**Comment by back2dos** [comment] 2015-06-26 11:47
Well, this would work:

```
var groupOfEngines:Array<{function takeOff():Void;}> = [
  new SpecialEngine(),
  new OldEngine(),
];
```

Although I'm not sure that's what you are after. The clearest way to define things would be to have an interface called `Engine` and have everything that _is a_ `Engine` implement it. If you find yourself having too many classes implementing too many interfaces, it may well be that you're generally having objects that are too fat.

**Comment by 5Mixer** [comment] 2015-06-26 11:53
Well, I don't know what you mean by fat objects, but I think I might just go with interfaces that define what an object does, and certain standard classes I forward to actually implement some behaviour. I see this as having a number of uses, such as the fact I can iterate and the compiler knows what methods it has implemented, and I can use Std.is. So, I might have a rocketInterface, a swordInterface, and a fuelInterface. Then, I might have, for example, a sword that glows implementing the swordInterface. And then, if I want different functioning swords, I can forward it to the glowingSword class but change any methods I wish. With any of these numerous glowing swords, I can do Std.is to reveal is is a swordInterface, and can iterate over it.

Woo! The feeling of understanding your own code is great! Now let's see if I can actually implement it... heh...
Thanks again, very much.

_Saves page. Screenshots page. Bookmarks page. Writes down page. :P_

**Comment by back2dos** [comment] 2015-06-26 13:05
Well, there is nothing wrong with having an `interface Sword` or an `interface Fluent` or what not. I'm just saying that if it feels like it's becoming to tedious, then maybe that's because you are doing too much at the same time.

Also, the interfaces can be a little more genereric. For example `Weapon` which works for both swords and clubs and lasers. Or `Propulsion` which might be a jet engine, but might also be a sail. And interface should clarify **what** an object does, not how. 

And also, you don't have to forward to the same type as the one you are implementing. You can `implement Weapon` which demands an `attack` method, but get that by forwarding to e.g. `VisciousMuffin`, which it self doesn't implement `Weapon` but happens to have has a compatible `attack` method.

I hope that clarifies things a little :)

**Comment by 5Mixer** [comment] 2015-06-27 04:22
Hey, thanks for this. The implementation has been going perfectly, except one thing. 

Let's say I have an ItemSlot class. This class contains a variable of it's contents (which is an object containing quantity, type etc.) For most slots, this contents object will be of type ItemStack, however, I also have fuel items. Fuel items have extra properties such as burn time (as well as quantities, type...), and thus they implement ItemStack, (so they can be stored in the contents variable, like most items) but they also implement burnable. Now the issue is, that I can store these in the slots, but I can't get it's burn time property, as it is storing it only as an ItemStack, not as a burnable.

I have tried various things such as making the contents variable dynamic, and casting it, neither of which worked.
Do you have any ideas on how I could get this to work? Really annoyed I got this far only to be stopped by an issue like this. Thanks! :)

**Comment by 5Mixer** [comment] 2015-06-27 04:25
Hmm, that was a very confusing comment. Consider...

Interface: A
Interface: B

Variable X implementing A&B.
Variable of type: K, which is type A
Set K to X
How can I get both A and B from K?

**Comment by 5Mixer** [comment] 2015-06-27 04:36
I obviously can't just make the type like coal or the exact object as there will be different types, thats why I am using interfaces.

**Comment by 5Mixer** [comment] 2015-06-27 05:31
Been struggling with this for an hour, and haven't achieved much. I don't think it's impossible though because doing Type.typeof(K) reveals it stores some info on it's fuel attributes, however the Type system knows that some items might not have those properties, so it won't let me access them.

_rambles to self._

**Comment by 5Mixer** [comment] 2015-06-27 05:39
I have it! Sorry. Gee, your email quota must be full :O Anyway, casting worked, but at the first instance it ran my object was null so it failed. I fail for the worst reasons :/ Ah well, least it didn't cost you time. All good! Syntactic delegation is so useful.

**Comment by back2dos** [comment] 2015-06-27 09:46
It seems this issue has become your [rubber duck](https://en.wikipedia.org/wiki/Rubber_duck_debugging) :D

**Comment by 5Mixer** [comment] 2015-06-27 09:58
Haha, I was talking to myself today line by line! Yeah sorry about spam lol. Never heard of the term before, it's pretty funny ;P

**Comment by back2dos** [comment] 2016-01-21 20:58
Ok, I'm closing this, since it seems settled ;)

**Closed as completed by back2dos** 2016-01-21 20:58 UTC
